apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: gateway-agcoolstoresm
spec:
  hosts:
  - "*"
  gateways:
  - istio-gateway
  http:
  - match:
    - uri:
        prefix: /agcoolstoresm/api
    rewrite:
      uri: "/api"
    route:
    - destination:
        port:
          number: 8080
        host: gateway
